sudo: required
dist: trusty
language: cpp
compiler:
    - clang
    - gcc

addons:
  apt:
    packages:
    - libgtest-dev
    - g++-multilib
    - gcc-multilib
    - gcc-avr
    - avr-libc

env:
    - CFLAGS="-Werror" CXXFLAGS="-Werror"

before_install:
    - mkdir gtest-build
    - pushd gtest-build
    - CXXFLAGS='-m32' CFLAGS='-m32' cmake /usr/src/gtest
    - make
    - popd

script:
    # Building and running unit tests
    - mkdir build
    - cd build
    - CMAKE_LIBRARY_PATH=../gtest-build/ cmake ../tests
    - make
    - ./run_tests
    - cd ..
    # Building the AVR driver (TODO: skip this during Clang build)
    - mkdir build-avr
    - cd build-avr
    - cmake ../drivers/avr
    - make
